### ISSUE TITLE
Men Can you help me with this

### ISSUE THREAD

**Issue by Vanegas9090** [ChasakisD/Xamarin.Forms.BackgroundKit#27]
![image](https://user-images.githubusercontent.com/28068090/60638902-76ebaa00-9ddd-11e9-89cc-3a5899ccc6eb.png)

**Comment by ChasakisD** [comment]
On line 9, remove the ".Chips" from the namespace. This is targeting to XamarinBackgroundKit.Controls.Chips instead of XamarinBackgroundKit.Controls.

@Vanegas9090 please reopen the issue if the problem persists

**Comment by Vanegas9090** [comment]
Thanks now it shows me the MaterialCard and MaterialContentView
 just only a question

how can I do to make a gradient button?

**Comment by ChasakisD** [comment]
You have to use the BackgroundEffect in order to add background to Xamarin.Forms views. 

To set a gradient to Background there are three ways as described in the README.md.

If you want a gradient with only 2 colors you can use:
```xml
<Button
    controls:BackgroundEffect.Background="{controls:BgProvider GradientBrush={controls:LinearGradient Start=Red, End=Green, Angle=70}}" />
```

If you want a gradient with more than 2 colors you can use:
```xml
<Button
    controls:BackgroundEffect.Background="{controls:BgProvider GradientBrush={controls:LinearGradient Gradients='Red,Green,Blue', Angle=70}}" />
```
Otherwise you can use the old way:
```xml
<Button>
    <controls:BackgroundEffect.Background>    
        <controls:Background>
            <background:Background.GradientBrush>
                <background:LinearGradientBrush Angle="45">
                    <background:GradientStop Offset="0" Color="DarkBlue" />
                    <background:GradientStop Offset="1" Color="DarkRed" />
                </background:LinearGradientBrush>
            </background:Background.GradientBrush>
        </controls:Background>
    </controls:BackgroundEffect.Background>
</Button>
```

PS: There is a workaround for an issue when the gradient is not working. If this is happening, try specifying the Color property to the Background.

**Comment by Vanegas9090** [comment]
Okay dude, Thank you

**Comment by Vanegas9090** [comment]
I think this is the issue you were saying before right?
![image](https://user-images.githubusercontent.com/28068090/60679930-a2ef4580-9e46-11e9-8c7d-a4f46434de4b.png)

**Comment by ChasakisD** [comment]
@Vanegas9090 I don't think those controls and effects work on preview. I actually never use the preview, so I never tested it. Btw, yes in order for the gradient to work on android, specify the Color to Background class for example to white. The color will be ignored and the gradient it will draw fine. This issue is addressed and will be fixed pretty soon.

**Comment by Vanegas9090** [comment]
you know the gradient works on my preview actually I was showing you the console Error log

when I try to compile the project show me Type background:GradientStop not found

**Comment by ChasakisD** [comment]
Oh, there is an issue when using the url on xmlns. Please check issue #21 in order to fix it.

**Comment by Vanegas9090** [comment]
the same man 
![image](https://user-images.githubusercontent.com/28068090/60726310-772c9800-9ef8-11e9-8b6e-b11b51546a26.png)

**Comment by Vanegas9090** [comment]
at the top are the xmlns references and the button code below

**Comment by ChasakisD** [comment]
Lines 21-26, replace background: with control:

**Comment by Vanegas9090** [comment]
It works! Men thank you for everything you're the best

![image](https://user-images.githubusercontent.com/28068090/60726657-4c8f0f00-9ef9-11e9-8290-c0a7f903d7d5.png)
