### ISSUE TITLE
XF 4 dependency

### ISSUE THREAD

**Issue by kicsiede** [ChasakisD/Xamarin.Forms.BackgroundKit#39]
hello,

is there any reason you need an exact xf version dependency? unfortunatelly i cannot upgrade to 4.*, and stuck with 3.6

fyi you can specify package-ranges like this in the csproj:
`<PackageReference Include="Xamarin.Forms" Version="(*,4.0.0.0)" />`

**Comment by ChasakisD** [comment]
Is there any 3.x version of Xamarin.Forms where Visual.Material exists? 

The only reason for the 4.x dependency is because on iOS, the shadow is drawn by the MDCShadowLayer and ripple is drawn by the MDCInkViewController. Both of those are existing in iOS MaterialComponents that came with Visual.Material

**Comment by kicsiede** [comment]
I'm using Visual.Material just fine with 3.6. :) afaik it was introduced in 3.3 or maybe even earlier. However it is extension to XF 3.* indeed, called Xamarin.Forms.Visual.Material.

(I'm using only visual=material for buttons though, don't know about the components you mentioned)

**Comment by ChasakisD** [comment]
Oh, seems there is a 3.x version of Visual.Material and more specifically is 3.5.0.129452. 

I will update the dependency to that version and when the nuget is published I will comment here.

[MaterialComponents](https://github.com/material-components/material-components-ios) is a library supported by Google in order to bring Material UI to iOS. Microsoft created binding of that library and shipped it with Xamarin.Forms.Visual.Material.

MaterialComponents contains all the goodies of Material UI like ripple animation, elevation and a huge list of components

**Comment by kicsiede** [comment]
i recommend using the package-range method i mentioned in the first post, so that users of your library can use any version they want above 3.5.0.129452!

**Comment by ChasakisD** [comment]
There is no need to specify a range. By specifying a version on .nuspec, any version that is after the specified version can be used.

**Comment by ChasakisD** [comment]
@kicsiede The issue has been fixed on skia-support branch on commit 1683ed0. The fix will be available in Release 1.3.0

**Comment by kicsiede** [comment]
@ChasakisD it would be nice if you published a 1.2.1 service release with this sooner though... 1+ month is a bit much to wait! ;)

**Comment by ChasakisD** [comment]
@kicsiede Version 1.2.1 according to branch nuget-dependencies-fix was released to nuget. It will be listed soon.

**Comment by kicsiede** [comment]
@ChasakisD thanks man! :)
