### ISSUE TITLE
[bug] [iOS] strange background animations on MaterialContentView when size changes

### ISSUE THREAD

**Issue by kicsiede** [ChasakisD/Xamarin.Forms.BackgroundKit#41]
hello,

on iOS when dynamically changing the size of a MaterialContentView some weird animations happen which i am unable to turn off. this inevitably happens for example if a ListView.ViewCell reusing/rebinding the previously disappearing cell template.

sometimes even rendering becomes incorrect for the corners when rebinding the margin: see attached example when tapping on a row. This i guess happens due to the fact that the curvature is calculated to the previous width/height of the view, but the background is stretched to the new size.

So the fix is probably listening to sizechange events of the host, and recalculating the background accordingly. (there is also an issue when IsCircle == true, and padding > 0, these maybe related to each other)

repro: [IOSBug.zip](https://github.com/ChasakisD/Xamarin.Forms.BackgroundKit/files/3439067/IOSBug.zip)

other than that: it is a great library! :)

**Comment by ChasakisD** [comment]
Hey @kicsiede,

Thanks for the feedback and the reproduction link! After checking the project, my opinion is that something strange is happening either with the clipping or with the path calculation of the GradientStrokeLayer. I will make a page into my example project to replicate this issue and start working on it. 

IsCircle is kinda buggy when using it with padding. The best way is to specify exactly the CornerRadius or use the IsCornerRadiusHalfHeight property. Please fill an issue with the IsCircle property.

The animations that are happening are because changes on CALayers are animated. I don't know if there is a way to prevent them from happening. I'll search for it.

Thanks again!

**Comment by ChasakisD** [comment]
The problem is with GradientStrokeLayer. When margin is changed, ```DrawInContext``` is never called, so the round corners path is never updated. Looking into it right now

**Comment by ChasakisD** [comment]
@kicsiede i have a fix-ready for the issue with round corners. I will soon make a PR and upload a new 1.2.2 version :)

**Comment by kicsiede** [comment]
@ChasakisD while trying to workaround the problem I've found that CardView is also facing a similar issue, but maybe unrelated, so trying to create a repro first

**Comment by ChasakisD** [comment]
The problem was on InvalidateLayer on MaterialBackgroundManager. MaterialCard also uses that manager and GradientStrokeLayer, and since the problem was that on resize, the layer was not redrawn, this will also fix the issue for MaterialCard.

**Comment by ChasakisD** [comment]
Please feel free to create separate issues for the IsCircle and animation when view is resized, so i can track them differently. Version 1.2.2 published to nuget and will be listed soon!

**Comment by kicsiede** [comment]
@ChasakisD sorry, false alert, i wasn't aware that CardView doesn't support different radius for each corners!

thanks for the fast fix! :)
