### ISSUE TITLE
[bug] ios CAAnimations when size changes

### ISSUE THREAD

**Issue by kicsiede** [ChasakisD/Xamarin.Forms.BackgroundKit#43]
hello,

i think this is what you need in :

```
            CATransaction.Begin();
            CATransaction.DisableActions = true;
            // update CALayer here
            CATransaction.Commit();
```

please note, that this shouldn't be optional, since the animation only applies to the background layer, the container (along with elevation shadow etc) is updated instantly, which leads to really ugly half animated updates. (when scrolling through a listview for example)

**Comment by ChasakisD** [comment]
The thing here is that I do not use a CATransaction to update the Layer. I just redraw it. I will look into it and I agree that this should not be optional.

Edit: The animation is triggered when updating the Frame of CALayer. So, wrapping it into a CATransaction actually disabled the Animation! Feel free to update the ```InvalidateLayer``` method of ```MaterialBackgroundManager``` since you figured out the solution, and make a PR :)

**Comment by kicsiede** [comment]
@ChasakisD please go ahead, i wouldn't even know where to look, and more importantly i'm really behind my schedules :)
