### ISSUE TITLE
[bug] [Android] BorderStyle==Outer seems to be ignored (always Inner)

### ISSUE THREAD

**Issue by kicsiede** [ChasakisD/Xamarin.Forms.BackgroundKit#44]
hello,

on Android border is always covered and cannot be made visible if the content fills the whole area.

see attached sample for repro: [AndroidBug.zip](https://github.com/ChasakisD/Xamarin.Forms.BackgroundKit/files/3439180/AndroidBug.zip)

iOS seems ok in that regard. however I'm still not really sure if the intended behaviour for "Inner" is to be able to cover the border by the content.

**Comment by ChasakisD** [comment]
Hi @kicsiede,

Maybe the Inner/Outer is not the best name to describe what I mean. When BorderStyle is set to Inner, the child view will be clipped to parent bounds. When the BorderStyle is set to Outer, the child view will be clipped in the parent bounds - border width. So the border will become visible.

This is the purpose of the BorderStyle.

Although the bug is happening because I ignore the clipping if the CornerRadius is Empty or the radius is same on each corner, ignoring the border style. Will make a PR soon that fixes this issue.

**Comment by ChasakisD** [comment]
@kicsiede Version 1.2.3 uploaded to nuget!

**Comment by kicsiede** [comment]
@ChasakisD thanks! now everything looks awesome on both iOS & Android! :)
