### ISSUE TITLE
Support ShadowColor

### ISSUE THREAD

**Issue by bentmar** [ChasakisD/Xamarin.Forms.BackgroundKit#51]
In many design suggestion the shadow is much more subtle or its just not black. I gave your code a glimpse and saw that this should be pretty easy to add. 

For iOS both GradientStrokeLayer and MDCCard support setting a shadowcolor.

for Android API 28 MaterialCardView supports .SetOutlineAmbientShadowColor and .SetOutlineSpotShadowColor

I would love to see this feature! 

Thanks!

**Comment by ChasakisD** [comment]
Hi @bentmar 

Thanks for your feedback!

I've seen those methods on API 28. I tried to implement custom shadow drawing on Android in order to support shadow color and offsets. But, Android draws shadow on a software layer. So the whole view must be drawn on a software layer, which means no hardware acceleration at all. I think those API 28 methods are (by now) the only way to implement it on Android.

Supporting shadow colors is in my roadmap, but because i'm a little busy to finish the PR #50, feel free to make a PR if you want to :)

**Comment by bentmar** [comment]
I have a finished implementation for android and ios now :)  (i couldnt stop myself). its based on your master branch. How do u want the code since im not allowed to push i to this repo

**Comment by bentmar** [comment]
i could just drop it as a feature branch if youd let me :)

**Comment by ChasakisD** [comment]
Just fork the repo and make a PR targetting master branch :)
