### ISSUE TITLE
Type BgProvider not found

### ISSUE THREAD

**Issue by agusibrahim** [ChasakisD/Xamarin.Forms.BackgroundKit#55]
hi @ChasakisD, i found error with your BackgroundKit. 
`Type BgProvider not found in xmlns http://xamarin.com/schemas/2014/forms/background`
in xamarin previewer just fine, but when I build the project an error occurs
I'm using visual studio for mac 8.3.7
please the solution

**Comment by ChasakisD** [comment]
Please confirm that your assembly contains a PackageReference to Xamarin.Forms Nuget Package. If not, add the Xamarin.Forms nuget package to that project. If this does not help, create a static class with a static constructor and just add the following
```cs
var x = typeof(MaterialContentView);
```

There are some cases where the xmlns is not working because there are no references in C# code.

**Comment by agusibrahim** [comment]
It's work, i've added new static class like advice from you.  thanks...

**Comment by JohamVan** [comment]
It works but only Debug mode for Android and iOS. When i try to compile the project in Release mode, VS throws the same error: Type BgProvider not found in xmlns http://xamarin.com/schemas/2014/forms/background. 

I'm using Visual Studio Community 16.4.3
Thanks in advance for your help.

**Comment by RichardSV15** [comment]
@JohamVan Where you able to resolve the issue? I am experiencing the same issue 
Using Visual Studio Community 16.5.1

**Comment by JohamVan** [comment]
@RichardSV15  I didn't able to resolve this issue, so I changed this plugin to PancakeView and the headache disappeared.
